import './globals.css'
import { Metadata } from 'next'
import { ReactNode } from 'react'

export const metadata: Metadata = {
  title: 'Chatapp',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: {
  children: ReactNode
}) {
  return (
    <html lang='en'>
      <head>
        {/* eslint-disable-next-line @next/next/no-page-custom-font */}
        <link href='https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined&display=optional' rel='stylesheet' />
      </head>
      <body>
        {children}
      </body>
    </html>
  )
}
